apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: perf-pushgateway
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pushgateway-perf-monitoring
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pushgateway-perf-monitoring
    app.kubernetes.io/part-of: perf-monitoring
  name: pushgateway-perf-monitoring
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app.kubernetes.io/component: perf-pushgateway
    app.kubernetes.io/instance: pushgateway-perf-monitoring
    app.kubernetes.io/name: perf-monitoring
status:
  loadBalancer: {}
