apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pushgateway-perf-monitoring
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pushgateway-perf-monitoring
    app.kubernetes.io/part-of: perf-monitoring
  name: pushgateway-perf-monitorigcs4
spec:
  port:
    targetPort: 9091
  tls:
    termination: edge
  to:
    kind: Service
    name: perf-pushgateway-service
    weight: null
status: {}
